import crypto from 'crypto';
import { ChallengeState, MathDomain } from '../types';
import { COMMANDER_CONFIG, MathDifficulty } from './config';

export const ENERGY_REWARD_EASY = COMMANDER_CONFIG.math.rewards.EASY.energy;
export const ENERGY_REWARD_MEDIUM = COMMANDER_CONFIG.math.rewards.MEDIUM.energy;
export const ENERGY_REWARD_HARD = COMMANDER_CONFIG.math.rewards.HARD.energy;
export const ENERGY_REWARD_EXPERT = COMMANDER_CONFIG.math.rewards.EXPERT.energy;

interface Problem {
  domain: MathDomain;
  question: string;
  answer: string;
  difficulty: MathDifficulty;
}

const PROBLEM_POOL: Problem[] = [
  { domain: MathDomain.Arithmetic, question: "Find the smallest number to be added to $157$ so that $12$ divides the sum exactly.", answer: "11", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "What least number must be subtracted from $185$ to get a number exactly divisible by $11$?", answer: "9", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If the sum of two numbers is 14 and their difference is 10, find the product of these two numbers.", answer: "24", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $m=-4$ and $n=-2$, find the value of $m^3-3m^2+3m+3n+3n^2+n^3$.", answer: "-126", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "How many three-digit numbers are multiples of 9?", answer: "100", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Two consecutive even positive integers have a sum of squares equal to 884. Find the smaller integer.", answer: "20", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The sum of the digits of a two-digit number is 12 and the difference between its two digits is 6. If the number is less than 50, what is the number?", answer: "39", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find the difference between the greatest and the least four-digit numbers that begin with 3 and end with 5.", answer: "990", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "By how many of the following numbers is $2^6-1$ divisible? $2,3,5,7,9$", answer: "3", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "In a division sum, the quotient, dividend and remainder are 15, 940 and 25 respectively. Find the divisor.", answer: "61", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "In a division sum, the divisor is 12 times the quotient and 5 times the remainder. If the remainder is 48, find the dividend.", answer: "4848", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The divisor is 25 times the quotient and 5 times the remainder. If the quotient is 16, find the dividend.", answer: "6480", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "How many numbers less than 200 are multiples of both 6 and 8?", answer: "8", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "How many integers between 100 and 150, both inclusive, can be evenly divided by neither 3 nor 5?", answer: "27", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The last digit in the decimal representation of \(\left(\frac{1}{5}\right)^{2000}\) is", answer: "6", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If \(78*3945\) is divisible by 11, where \(*\) is a digit, then \(*\) is equal to?", answer: "5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Which digit will replace H in the following equation? 9H + H8 + H6 = 230", answer: "6", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If \(a=11\) and \(b=9\), then twice the value of \(\frac{a^2+b^2+ab}{a^3-b^3}\) is?", answer: "1", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Two numbers are in the ratio 5:6. Their L.C.M. is 210. Find the sum of the two numbers.", answer: "77", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The H.C.F. of two numbers is 17 and their L.C.M. is 1020. If one of the numbers is 68, find the other number.", answer: "255", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The sum of two numbers is 450 and their highest common factor is 18. What is the total number of pairs of positive integers that satisfy these conditions?", answer: "10", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The H.C.F. of 4 × 27 × 125, 8 × 9 × 25 × 7 and 16 × 81 is", answer: "36", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find the highest common factor of 48 and 72.", answer: "24", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "First reduce each fraction to its lowest terms. The H.C.F. of fractions is obtained by taking the H.C.F. of the numerators and the L.C.M. of the denominators. Find the H.C.F. of $\frac{6}{12}$, $\frac{9}{18}$, and $\frac{15}{24}$. If the H.C.F. in lowest terms is $\frac{p}{q}$, find $p+q$.", answer: "9", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The L.C.M. of fractions is obtained by taking the L.C.M. of the numerators and the H.C.F. of the denominators. Using this rule, find the L.C.M. of $\frac{2}{3}, \frac{4}{6}, \frac{6}{9}$. If the L.C.M. in lowest terms is $\frac{p}{q}$, find $p+q$.", answer: "$5$", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The product of two numbers is 2160 and their H.C.F. is 12. The number of such pairs is ?", answer: "2", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Three numbers are in the ratio of 2 : 3 : 5 and their L.C.M. is 1800. Their H.C.F. is ?", answer: "60", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The L.C.M. and ratio of four numbers are 840 and 2 : 3 : 5 : 7 respectively. The difference between the greatest and least numbers is ?", answer: "20", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The H.C.F. and L.C.M. of two numbers are 18 and 648 respectively. If the ratio of the two numbers is 4 : 9, then the larger of the two numbers is ?", answer: "162", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "L.C.M. of two prime numbers x and y (x > y) is 95. The value of 3y - x is ?", answer: "-4", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The ratio of two numbers is 13:15 and their L.C.M. is 585. What is the sum of the two numbers?", answer: "84", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The number of zeros at the end of the product $5 \times 10 \times 15 \times 20 \times 25 \times 30$ is", answer: "4", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $x+y=15$ and $xy=56$, then what is the value of $x^2+y^2$?", answer: "113", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The sum of two consecutive even numbers is $50$. What is the sum of the next two consecutive even numbers?", answer: "58", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The number of prime factors, counting multiplicity, in the expression $6^{10} \times 7^{17} \times 11^{27}$ is", answer: "64", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "What is the number of distinct prime factors contained in the product $30^7 \times 22^5 \times 34^{11}$?", answer: "5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "What number multiplied by $48$ will give the same product as $173$ multiplied by $240$?", answer: "865", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "For an integer $n$, $n! = n(n-1)(n-2)\cdots 3\cdot2\cdot1$. Then, $1!+2!+3!+\cdots+50!$ leaves what remainder when divided by $7$?", answer: "5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Convert $0.625$ into a fraction in its simplest form. If the fraction is $\frac{p}{q}$, find $p+q$.", answer: "13", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Convert $0.045$ into a fraction in its simplest form. If the fraction is $\frac{p}{q}$, find $p+q$.", answer: "209", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If \(\frac{b}{a}=\frac{2}{3}\), then what is the value of \(\frac{2a-b}{2a+b}+\frac{2}{9}\)? If the answer is expressed as \(\frac{p}{q}\) in its lowest form, find \(p+q\).", answer: "31", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Given that $275 \times 36 = 9900$, find the value of $2.75 \times .36$.", answer: "0.99", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "12.5 + 3.6 - 2.1 = ?", answer: "14", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "25.4 - 6.2 + 3.8 = ?", answer: "23", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "8.5 + 4.2 - 1.7 = ?", answer: "11", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Solve $\frac{4}{7}$ of $\frac{7}{10}$ of $\frac{5}{12}$ of 840 = ?", answer: "140", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $3x + 2y = 40$ and $\frac{x+y}{y} = \frac{17}{11}$, find the value of $7x + 5y$.", answer: "97", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The cost of 2 bags and 3 boxes is ₹390, while the cost of 5 bags and 2 boxes is ₹590. What is the cost of one bag?", answer: "90", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find the value of $\left(1-\frac{1}{4}\right)\left(1-\frac{1}{5}\right)\left(1-\frac{1}{6}\right)\cdots\left(1-\frac{1}{60}\right)$. If the answer in lowest terms is $\frac{p}{q}$, find $p+q$.", answer: "21", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find the value of $\frac{1}{2\times4}+\frac{1}{4\times6}+\frac{1}{6\times8}+\cdots+\frac{1}{14\times16}$. If the answer in lowest terms is $\frac{p}{q}$, find $p+q$.", answer: "39", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "A man was asked to multiply a certain number by 75. He multiplied it by 48 and got his answer less than the correct one by 1350. Find the number to be multiplied.", answer: "50", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The cost of 4 rings and 2 bangles is ₹1200. What is the cost of 6 rings and 3 bangles?", answer: "1800", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\star$ is an operation such that $x\star y=2x+5y$, find the value of $3\star4+6\star2$.", answer: "48", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $a^2+b^2=25$, $ab=12$, and $a>b>0$, find the value of $\frac{a+b}{a-b}$. If the answer is expressed as $\frac{p}{q}$ in its lowest form, find $p+q$.", answer: "8", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $(x-2)^3+(x-6)^3+(x-4)^3=3(x-2)(x-6)(x-4)$, find the value of $x$.", answer: "4", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $x$ is an integer such that $x + \frac{1}{x} = \frac{5}{2}$, find the value of $x - \frac{1}{x}$. If the answer is expressed as $\frac{p}{q}$ in its lowest form, find $p+q$.", answer: "5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "When an amount was distributed among 6 boys, each boy received ₹20 more than the amount received by each boy when the same amount was distributed equally among 8 boys. What was the total amount?", answer: "480", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "In an objective examination of 100 questions, 5 marks are allotted for every correct answer and 2 marks are deducted for every wrong answer. If all 100 questions were attempted and the student got a total of 388 marks, how many questions were attempted wrong?", answer: "16", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "A person has 70 currency notes, some of ₹100 denomination and the remaining of ₹25 denomination. If the total amount is ₹4750, how many ₹25 notes are there?", answer: "30", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "In a group of 75 people, 55 like coffee, 42 like tea and each person likes at least one of the two drinks. Find the number of people who like both coffee and tea.", answer: "22", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $A+B=96$ and $A$ is half of $B$, then the value of $A$ will be", answer: "32", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$\frac{4+9\div3\times2}{6+5\times4\div2}=\frac{p}{q}$ in lowest form. Find $p+q$.", answer: "13", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\frac{1}{4}+\frac{1}{3}+\frac{1}{x}=3$ and $x=\frac{p}{q}$ in lowest form, find $p+q$.", answer: "41", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\frac{x}{2y}=\frac{5}{6}$, then $\frac{x-y}{x+y}+\frac{7}{8}=\frac{p}{q}$ in lowest form. Find $p+q$.", answer: "17", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\frac{a}{b}=\frac{5}{6}$ and $\frac{b}{c}=\frac{9}{10}$, then $\frac{c^2-a^2}{c^2+a^2}=\frac{p}{q}$ in lowest form. Find $p+q$.", answer: "32", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If x = 7 - 3q and y = 2q + 2, then for what value of q is x equal to y?", answer: "1", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\frac{3a+b}{a+3b}=2$, then find the value of $\frac{a+b}{a+2b}$. If the answer is expressed as $\frac{p}{q}$ in its lowest form, find $p+q$.", answer: "13", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Riya has ₹5 more than Arjun and ₹8 more than Karan. All three have ₹44 in all. What is Riya's share?", answer: "19", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The sum of the weights of A and B is $96$ kg. Half of the weight of A is equal to $\frac{3}{4}$ of the weight of B. Find the weight of B.", answer: "38.4", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Neha is 3 years older than Priya, and Priya is 12 years older than Kavya. If their total age is 150 years, what is the value of (Priya's age + Kavya's age) - Neha's age?", answer: "38", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "A metal rod is 52.5 metres long. How many pieces of 75 cm length can be cut from it?", answer: "70", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "For a parade, 35 students were made to stand in each column and 16 columns were formed. If 20 students are made to stand in each column, how many columns can be formed?", answer: "28", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The cost of 6 pens and 3 pencils is ₹84. One-third of the cost of one pen is equal to the cost of one pencil. What is the total cost of 4 pens and 5 pencils?", answer: "68", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "A car company sold 240 cars in a special 6-day sale. Each day, the company sold 6 more cars than the previous day. How many cars were sold on the 6th day?", answer: "55", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "A group of 1530 persons consisting of captains and soldiers is travelling in a train. If for every 17 soldiers there is one captain, then the number of captains in the group is?", answer: "85", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "A mango costs ₹6 and an orange costs ₹4. Rahul spends ₹32 on these fruits. If he purchases $2$ oranges, how many mangoes does he purchase?", answer: "4", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If p = q = 2r and pqr = 864, then p = ?", answer: "12", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $5y+15x=180$ and $\frac{42x}{17y}=\frac{70}{17}$, then what is the value of $y-x$?", answer: "-4", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If 5x - 4y = 6 and x/(x + y) = 2/3, then what is the value of 2xy?", answer: "4", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If 2 jeans and 3 shirts cost ₹4900 and 3 jeans and 2 shirts cost ₹4600, what is the cost of 2 jeans and 1 shirt?", answer: "2700", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The cost of 6 pens and 4 pencils is ₹152, while the cost of 2 pens and 1 pencil is ₹49. What is the cost of 3 pens and 2 pencils?", answer: "76", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The cost of 2 dozen apples and 4 dozen bananas is ₹168. The cost of 1 dozen apples and 3 dozen bananas is ₹102. What is the price of 2 dozen bananas?", answer: "36", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The cost of 3 pencils, 1 pen and 2 erasers is ₹20, while the cost of 3 pencils, 5 pens and 4 erasers is ₹40. How much will 3 pencils, 3 pens and 3 erasers cost?", answer: "30", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "One-half of the sum of prime numbers, greater than 2 but less than 7, is the square of which number?", answer: "2", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The value of $\sqrt{19+\sqrt{26+\sqrt{93+\sqrt{45+\sqrt{16}}}}}$ is?", answer: "5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Evaluate $\sqrt{57-\sqrt{59+\sqrt{29-\sqrt{16}}}}$.", answer: "7", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$\sqrt{271+\sqrt{324}}$ is equal to?", answer: "17", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$\left(\frac{\sqrt{225}}{5}\right)\left(\frac{\sqrt{576}}{8}\right)\left(\frac{144}{\sqrt{256}}\right)=?$", answer: "81", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$300-\left[\frac{48}{4(2+1)}\right]\times5+6(14-9)=?$", answer: "310", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$\left\{\frac{144}{6+(3\times2)}\right\}[20-(7+5)]+11=?$", answer: "107", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$\frac{960}{5(3+1)}+8[17-(6+4)]-15=?$", answer: "89", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$400-\left\{\frac{72}{6+(3\times2)}+9(15-8)\right\}+18=?$", answer: "349", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$\left[\frac{120}{5+5}(18-6)\right]+7[20-(9+3)]-36=?$", answer: "164", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $x=\left(\frac{\sqrt{10}+\sqrt{5}}{\sqrt{10}-\sqrt{5}}\right)$ and $y=\left(\frac{\sqrt{10}-\sqrt{5}}{\sqrt{10}+\sqrt{5}}\right)$, find the value of $(x^2+y^2)$.", answer: "34", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find the value of $\sqrt{30+\sqrt{30+\sqrt{30+\cdots}}}$.", answer: "6", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "By what least number should $24$ be multiplied to obtain a number which is a perfect cube?", answer: "9", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find the value of $\sqrt{90.25}$.", answer: "9.5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find the exact value of $\sqrt{\frac{36}{100}-\frac{1}{25}}$.", answer: "$\frac{2\sqrt{2}}{5}$", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The digit in the unit's place in the square root of $17689$ is", answer: "3", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The value of $\sqrt{0.000729}$ is", answer: "0.027", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The value of $\sqrt{0.04}+\sqrt{0.25}+\sqrt{1.44}+\sqrt{0.0009}$ is", answer: "1.93", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\sqrt{4900}=70$, then the value of $\sqrt{49}+\sqrt{0.49}+\sqrt{0.0049}$, up to two places of decimals, is", answer: "7.77", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\frac{45}{x}=\sqrt{\frac{144}{256}}$, the value of $x$ is", answer: "60", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\sqrt{5^n}=125$, then the value of $n$ is", answer: "6", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\sqrt{8\times18\times x}=24$, then $x$ equals", answer: "4", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\sqrt{1+\frac{x}{144}}=\frac{13}{12}$, then $x$ is equal to", answer: "25", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Determine the value of $\frac{1}{\sqrt{9}+\sqrt{10}}+\frac{1}{\sqrt{10}+\sqrt{11}}+\frac{1}{\sqrt{11}+\sqrt{12}}+\cdots+\frac{1}{\sqrt{24}+\sqrt{25}}$.", answer: "2", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $x=\frac{\sqrt{7}+\sqrt{3}}{\sqrt{7}-\sqrt{3}}$ and $y=\frac{\sqrt{7}-\sqrt{3}}{\sqrt{7}+\sqrt{3}}$, then $(x+y)$ equals", answer: "5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $x=(3-2\sqrt{2})$, then the value of $\left(x+\frac{1}{x}\right)$ is", answer: "6", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $x=4+\sqrt{15}$, then $x^2+\frac{1}{x^2}$ is equal to", answer: "62", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $a=\frac{\sqrt{4}+\sqrt{3}}{\sqrt{4}-\sqrt{3}}$ and $b=\frac{\sqrt{4}-\sqrt{3}}{\sqrt{4}+\sqrt{3}}$, then the value of $a^2+b^2$ would be", answer: "194", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $a=\frac{\sqrt{9}+1}{\sqrt{9}-1}$ and $b=\frac{\sqrt{9}-1}{\sqrt{9}+1}$, and $\frac{a^2+ab+b^2}{a^2-ab+b^2}=\frac{p}{q}$ in lowest form, find $p+q$.", answer: "34", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "One-fourth of a herd of cows was seen in a field. Twice the square root of the number of cows in the herd had gone to another field, and the remaining $4$ cows were near a pond. Find the total number of cows.", answer: "16", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "A total of 200 oranges were distributed among a group of girls. Each girl got twice as many oranges as the number of girls in the group. How many girls were there?", answer: "10", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$\sqrt{\frac{21}{0.7}+4}+\sqrt{\frac{12}{0.4}+1}$ is equal to", answer: "$\sqrt{34}+\sqrt{31}$", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The body weights of five boys are recorded as $40$ kg, $50$ kg, $60$ kg, $45$ kg and $55$ kg. What is the average body weight of all five boys?", answer: "50", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find the average of the first $10$ multiples of $6$.", answer: "33", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Five persons went to a restaurant for dinner. Four of them spent ₹20 each, while the fifth person spent ₹30 more than the average expenditure of all five. What was the total money spent by all the persons?", answer: "₹137.50", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Of the three numbers, the second is twice the first and is also thrice the third. If the average of the three numbers is $44$, what is the largest number?", answer: "72", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The average of five numbers is $50$. The average of the first two numbers is $40$ and the average of the last two numbers is $45$. What is the third number?", answer: "80", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The average of $13$ papers is $40$. The average of the first $7$ papers is $44$ and that of the last $7$ papers is $36$. What are the marks of the seventh paper?", answer: "40", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The average of the odd numbers up to $20$ is", answer: "10", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "In a family, the average age of a father and a mother is $30$ years. The average age of the father, mother and their only son is $25$ years. What is the age of the son?", answer: "15", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Out of three numbers, the first is twice the second and is half of the third. If the average of the three numbers is $14$, then the difference between the first and third numbers is", answer: "12", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Of the three numbers, the average of the first and the second is greater than the average of the second and the third by $10$. What is the difference between the first and the third of the three numbers?", answer: "20", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The average weight of $A$, $B$ and $C$ is $30$ kg. If the average weight of $A$ and $B$ is $25$ kg and that of $B$ and $C$ is $28$ kg, what is the weight of $B$?", answer: "16", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The average age of $8$ persons is $30$ years. When the age of their instructor is added, the average age becomes $34$ years. What is the age of the instructor?", answer: "66", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The average of $8$ numbers is $12$. The average of $3$ of them is $10$. What is the average of the remaining numbers?", answer: "13.2", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "A number is as much greater than $30$ as it is less than $90$. Find the number.", answer: "60", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find a number such that when $10$ is subtracted from $6$ times the number, the result is $15$ more than twice the number.", answer: "6.25", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Three positive numbers are in the ratio $1:2:3$. The sum of their squares is $126$. Find the sum of the numbers.", answer: "18", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If the sum of two numbers is $10$ and the sum of their reciprocals is $\frac{5}{12}$, find the absolute difference between the two numbers.", answer: "2", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The product of two consecutive positive integers is $420$. Find the smaller integer.", answer: "20", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The sum of the squares of three consecutive positive odd integers is $251$. Find the middle integer.", answer: "9", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If the digits of a two-digit number are interchanged, the number formed is greater than the original number by $27$. If the difference between the digits is $3$ and their sum is $7$, what is the original number?", answer: "25", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If a positive number is multiplied by $\frac{2}{3}$ of itself, the value so obtained is $150$. What is the number?", answer: "15", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The sum of twice a number and three times $10$ is $80$. What is the sum of thrice the number and $10$?", answer: "85", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If one-third of one-fourth of a number is $5$, then three-tenths of that number is", answer: "18", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The ratio of the ages of A and B is $7:9$ respectively. Six years ago, the ratio of their ages was $5:7$ respectively. What is the present age of B?", answer: "27", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "A man's present age is one-half of the age of his mother. After $4$ years, he will be two-thirds of his mother's age. How old is the mother at present?", answer: "8", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The ages of A and B are in the ratio $5:4$ respectively. After $5$ years, the ratio of their ages will be $6:5$. What is the difference in their ages now?", answer: "5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Four years ago, a father was four times as old as his son. Four years hence, he will be twice as old as his son. What is the present age of the son?", answer: "8", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Eight years ago, a father was three times as old as his son. Now, the father is twice as old as his son. What is the sum of their present ages?", answer: "48", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Solve: $2^{1.5}\times3^{2.5}\times6^3\times2^{2.5}\times3^{1.5}=6^x$.", answer: "7", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $2^{x-1}+2^{x+1}=80$, then find the value of $x$.", answer: "5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $2^{x-1}+2^{x+1}=320$, then find the value of $x$.", answer: "7", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $16^x\cdot2^y=512$ and $7^{x+2y}=49^2$, then what is the value of $x+y$?", answer: "3", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$(27)^5\div(3)^8=?$", answer: "$3^7$", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\log_{16}8=\frac{p}{q}$ in lowest form, find $p+q$.", answer: "7", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\log_{10}(x^2-5x+76)=2$, find the positive value of $x$.", answer: "8", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "The value of $\log_{2\sqrt{3}}(1728)$ is", answer: "6", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\log_{25}x=0.5$, then $x$ is equal to", answer: "5", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\log_{10}2+\log_{10}(6x+1)=\log_{10}(x+2)+1$, then $x$ is equal to", answer: "9", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\log_{4}x+\log_{16}x^2+\log_{64}x^3=9$, then $x$ equals", answer: "64", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$10\%$ of $8$ and $5\%$ of $12$ add up to", answer: "1.4", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "200 candidates appeared for an examination, of which 150 passed. The pass percentage is", answer: "75", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$8$ kg of metal A and $12$ kg of metal B are mixed to form an alloy. The percentage of metal A in the alloy is", answer: "40", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$20\%$ of $300$ apples are rotten. How many apples are in good condition?", answer: "240", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$25\%$ of $80\%$ of $\frac{1}{2}$ of a number is $100$. What is $20\%$ of $\frac{1}{2}$ of that number?", answer: "100", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$125\%$ of $1600$ minus $75\%$ of a number is $500$. Find the number.", answer: "2000", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$20\%$ of $250$ + $30\%$ of $200$ = $50\%$ of a number. Find the number.", answer: "220", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Find the greatest possible integer for which $20\%$ of that number is less than or equal to $100$.", answer: "500", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$40\%$ of $75\%$ of $20\%$ of an amount is $480$. What is the amount?", answer: "8000", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "Three-fourths of a number is equal to $60\%$ of another number. The difference between the two numbers is $10$. What is the sum of the two numbers?", answer: "90", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "In a chemical mixture, $50\%$ is nitrogen and the rest is hydrogen and oxygen. If in $20$ kg of the mixture there are $6$ kg of oxygen, then what is the percentage of hydrogen in it?", answer: "20", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $m:n=3:2$, then $\frac{4m+5n}{4m-5n}=\frac{p}{q}$ in lowest form. Find $p+q$.", answer: "12", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $A$ exceeds $B$ by $50\%$, and $B$ is less than $C$ by $20\%$, then $A:C=\frac{p}{q}$ in lowest form. Find $p+q$.", answer: "11", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $(x+2):7=3:2$ and $x=\frac{p}{q}$ in lowest form, find $p+q$.", answer: "19", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $50\%$ of $A=\frac{2}{3}$ of $B$, then $A:B=\frac{p}{q}$ in lowest form. Find $p+q$.", answer: "7", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $\frac{1}{2}A=25\%$ of $B$, then $A:B=\frac{p}{q}$ in lowest form. Find $p+q$.", answer: "3", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $x:y=3:1$, then $(x^3-y^3):(x^3+y^3)=\frac{p}{q}$ in lowest form. Find $p+q$.", answer: "27", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "$\frac{2}{5}$ of $\frac{3}{4}$ of $800$ is equal to", answer: "240", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "5 workers working 2 hours a day can pack 10 boxes in 4 days. How many boxes can 10 workers working 4 hours a day pack in 2 days?", answer: "20", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "20 people consume 240 kg of rice in 12 days. In how many days will 30 people consume 300 kg of rice?", answer: "10", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "30 cows eat 30 bags of husk in 30 days. In how many days will one cow eat one bag of husk?", answer: "30", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $8$ persons working $4$ hours a day earn ₹9600 per week, then $6$ persons working $6$ hours a day will earn per week", answer: "₹10800", difficulty: 'MEDIUM' },
  { domain: MathDomain.Arithmetic, question: "If $5$ workers can collect $100$ kg of wheat in $4$ days, how many kilograms of wheat will $10$ workers collect in $3$ days?", answer: "150", difficulty: 'MEDIUM' }
];

function normalize(value: string): string {
  return value.toLowerCase().replace(/,/g, '').trim();
}

export class MathGenerator {
  public static generateChallenge(currentTurn: number): ChallengeState {
    const problem = PROBLEM_POOL[Math.floor(Math.random() * PROBLEM_POOL.length)];
    const reward = COMMANDER_CONFIG.math.rewards[problem.difficulty];
    return {
      id: crypto.randomUUID(),
      domain: problem.domain,
      difficulty: problem.difficulty,
      question: problem.question,
      correctAnswer: problem.answer,
      rewardEnergy: reward.energy,
      rewardTroops: reward.troops,
      expiresAtTurn: Number.MAX_SAFE_INTEGER,
      attempted: false,
    };
  }

  public static verifyAnswer(challenge: ChallengeState, submitted: string): boolean {
    return normalize(challenge.correctAnswer) === normalize(submitted);
  }
}
